apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-operator-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - create
    - list
    - get
    - watch
    - delete
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - '*'
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-operator-rolebinding
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chart.fullname" . }}-operator-role
subjects:
  - kind: ServiceAccount
    name: "k8sgpt
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "k8sgpt"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8sgpt-operator
    app.kubernetes.io/part-of: k8sgpt-operator
  {{- include "chart.labels" . | nindent 4 }}
